### ISSUE TITLE
Mi infografía

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/infografia-yanet-02#2]
[INFOGRAFIA-TRABAJO1.pdf](https://github.com/SistemasTecTlaxiaco/infografia-yanet-02/files/7125378/INFOGRAFIA-TRABAJO1.pdf)

**Comment by yaritzaov123** [comment]
20% , 
Considero que tú actividad tiene este valor porque está completo y cumple con todos los criterios que están consideradas en la rublica de evaluación

**Comment by josealfredo79** [comment]
Bien hecho y revisado
